// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALXvmMyKNZ5ut8uMqiiwGxKRKh_8PYv-M',
    appId: '1:767054575334:web:cd71078d98d2cccac66d27',
    messagingSenderId: '767054575334',
    projectId: 'usertrail-1234',
    authDomain: 'usertrail-1234.firebaseapp.com',
    storageBucket: 'usertrail-1234.firebasestorage.app',
    measurementId: 'G-P2ZBKD3DZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChkm6EX0oXJpNUK38o9TksYHjFd0W5RGA',
    appId: '1:767054575334:android:1f53d946cc05031ac66d27',
    messagingSenderId: '767054575334',
    projectId: 'usertrail-1234',
    storageBucket: 'usertrail-1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrVCidJUmRmb0hNPviIxP-yX8W_jwexDI',
    appId: '1:767054575334:ios:8e6c8de69a0ef0bdc66d27',
    messagingSenderId: '767054575334',
    projectId: 'usertrail-1234',
    storageBucket: 'usertrail-1234.firebasestorage.app',
    iosClientId: '767054575334-kvfkfmqprrk2l3tki6kea2uass3m1204.apps.googleusercontent.com',
    iosBundleId: 'com.example.users',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrVCidJUmRmb0hNPviIxP-yX8W_jwexDI',
    appId: '1:767054575334:ios:8e6c8de69a0ef0bdc66d27',
    messagingSenderId: '767054575334',
    projectId: 'usertrail-1234',
    storageBucket: 'usertrail-1234.firebasestorage.app',
    iosClientId: '767054575334-kvfkfmqprrk2l3tki6kea2uass3m1204.apps.googleusercontent.com',
    iosBundleId: 'com.example.users',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALXvmMyKNZ5ut8uMqiiwGxKRKh_8PYv-M',
    appId: '1:767054575334:web:ae62a55395c98442c66d27',
    messagingSenderId: '767054575334',
    projectId: 'usertrail-1234',
    authDomain: 'usertrail-1234.firebaseapp.com',
    storageBucket: 'usertrail-1234.firebasestorage.app',
    measurementId: 'G-PT6DRTCKCM',
  );
}
